# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from blotter import blotter_pb2 as blotter_dot_blotter__pb2


class BlotterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.LoadHistoricalData = channel.unary_unary(
        '/blotter.Blotter/LoadHistoricalData',
        request_serializer=blotter_dot_blotter__pb2.LoadHistoricalDataRequest.SerializeToString,
        response_deserializer=blotter_dot_blotter__pb2.LoadHistoricalDataResponse.FromString,
        )


class BlotterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def LoadHistoricalData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BlotterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'LoadHistoricalData': grpc.unary_unary_rpc_method_handler(
          servicer.LoadHistoricalData,
          request_deserializer=blotter_dot_blotter__pb2.LoadHistoricalDataRequest.FromString,
          response_serializer=blotter_dot_blotter__pb2.LoadHistoricalDataResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'blotter.Blotter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
