# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str


class ContractSpecifier(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class SecurityType(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'ContractSpecifier.SecurityType': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['ContractSpecifier.SecurityType']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'ContractSpecifier.SecurityType']]: ...
        STOCK = typing___cast('ContractSpecifier.SecurityType', 0)
        OPTION = typing___cast('ContractSpecifier.SecurityType', 1)
        FUTURE = typing___cast('ContractSpecifier.SecurityType', 2)
        INDEX = typing___cast('ContractSpecifier.SecurityType', 3)
        FUTURES_OPTION = typing___cast('ContractSpecifier.SecurityType', 4)
        CASH = typing___cast('ContractSpecifier.SecurityType', 5)
        CFD = typing___cast('ContractSpecifier.SecurityType', 6)
        COMBO = typing___cast('ContractSpecifier.SecurityType', 7)
        WARRANT = typing___cast('ContractSpecifier.SecurityType', 8)
        BOND = typing___cast('ContractSpecifier.SecurityType', 9)
        COMMODITY = typing___cast('ContractSpecifier.SecurityType', 10)
        NEWS = typing___cast('ContractSpecifier.SecurityType', 11)
        FUND = typing___cast('ContractSpecifier.SecurityType', 12)
    STOCK = typing___cast('ContractSpecifier.SecurityType', 0)
    OPTION = typing___cast('ContractSpecifier.SecurityType', 1)
    FUTURE = typing___cast('ContractSpecifier.SecurityType', 2)
    INDEX = typing___cast('ContractSpecifier.SecurityType', 3)
    FUTURES_OPTION = typing___cast('ContractSpecifier.SecurityType', 4)
    CASH = typing___cast('ContractSpecifier.SecurityType', 5)
    CFD = typing___cast('ContractSpecifier.SecurityType', 6)
    COMBO = typing___cast('ContractSpecifier.SecurityType', 7)
    WARRANT = typing___cast('ContractSpecifier.SecurityType', 8)
    BOND = typing___cast('ContractSpecifier.SecurityType', 9)
    COMMODITY = typing___cast('ContractSpecifier.SecurityType', 10)
    NEWS = typing___cast('ContractSpecifier.SecurityType', 11)
    FUND = typing___cast('ContractSpecifier.SecurityType', 12)

    class Right(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'ContractSpecifier.Right': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['ContractSpecifier.Right']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'ContractSpecifier.Right']]: ...
        UNSPECIFIED_RIGHT = typing___cast('ContractSpecifier.Right', 0)
        PUT = typing___cast('ContractSpecifier.Right', 1)
        CALL = typing___cast('ContractSpecifier.Right', 2)
    UNSPECIFIED_RIGHT = typing___cast('ContractSpecifier.Right', 0)
    PUT = typing___cast('ContractSpecifier.Right', 1)
    CALL = typing___cast('ContractSpecifier.Right', 2)

    symbol = ... # type: typing___Text
    securityType = ... # type: ContractSpecifier.SecurityType
    lastTradeDateOrContractMonth = ... # type: typing___Text
    strike = ... # type: typing___Text
    right = ... # type: ContractSpecifier.Right
    multiplier = ... # type: typing___Text
    exchange = ... # type: typing___Text
    currency = ... # type: typing___Text
    localSymbol = ... # type: typing___Text
    primaryExchange = ... # type: typing___Text
    tradingClass = ... # type: typing___Text
    includeExpired = ... # type: builtin___bool

    def __init__(self,
        *,
        symbol : typing___Optional[typing___Text] = None,
        securityType : typing___Optional[ContractSpecifier.SecurityType] = None,
        lastTradeDateOrContractMonth : typing___Optional[typing___Text] = None,
        strike : typing___Optional[typing___Text] = None,
        right : typing___Optional[ContractSpecifier.Right] = None,
        multiplier : typing___Optional[typing___Text] = None,
        exchange : typing___Optional[typing___Text] = None,
        currency : typing___Optional[typing___Text] = None,
        localSymbol : typing___Optional[typing___Text] = None,
        primaryExchange : typing___Optional[typing___Text] = None,
        tradingClass : typing___Optional[typing___Text] = None,
        includeExpired : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ContractSpecifier: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"currency",u"exchange",u"includeExpired",u"lastTradeDateOrContractMonth",u"localSymbol",u"multiplier",u"primaryExchange",u"right",u"securityType",u"strike",u"symbol",u"tradingClass"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"currency",b"currency",u"exchange",b"exchange",u"includeExpired",b"includeExpired",u"lastTradeDateOrContractMonth",b"lastTradeDateOrContractMonth",u"localSymbol",b"localSymbol",u"multiplier",b"multiplier",u"primaryExchange",b"primaryExchange",u"right",b"right",u"securityType",b"securityType",u"strike",b"strike",u"symbol",b"symbol",u"tradingClass",b"tradingClass"]) -> None: ...

class Duration(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class TimeUnit(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'Duration.TimeUnit': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['Duration.TimeUnit']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'Duration.TimeUnit']]: ...
        SECONDS = typing___cast('Duration.TimeUnit', 0)
        DAYS = typing___cast('Duration.TimeUnit', 1)
        WEEKS = typing___cast('Duration.TimeUnit', 2)
        MONTHS = typing___cast('Duration.TimeUnit', 3)
        YEARS = typing___cast('Duration.TimeUnit', 4)
    SECONDS = typing___cast('Duration.TimeUnit', 0)
    DAYS = typing___cast('Duration.TimeUnit', 1)
    WEEKS = typing___cast('Duration.TimeUnit', 2)
    MONTHS = typing___cast('Duration.TimeUnit', 3)
    YEARS = typing___cast('Duration.TimeUnit', 4)

    count = ... # type: builtin___int
    unit = ... # type: Duration.TimeUnit

    def __init__(self,
        *,
        count : typing___Optional[builtin___int] = None,
        unit : typing___Optional[Duration.TimeUnit] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Duration: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"count",u"unit"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"count",b"count",u"unit",b"unit"]) -> None: ...

class LoadHistoricalDataRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class BarSize(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'LoadHistoricalDataRequest.BarSize': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['LoadHistoricalDataRequest.BarSize']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'LoadHistoricalDataRequest.BarSize']]: ...
        UNSPECIFIED_SIZE = typing___cast('LoadHistoricalDataRequest.BarSize', 0)
        ONE_SECOND = typing___cast('LoadHistoricalDataRequest.BarSize', 1)
        FIVE_SECONDS = typing___cast('LoadHistoricalDataRequest.BarSize', 5)
        TEN_SECONDS = typing___cast('LoadHistoricalDataRequest.BarSize', 10)
        FIFTEEN_SECONDS = typing___cast('LoadHistoricalDataRequest.BarSize', 15)
        THIRTY_SECONDS = typing___cast('LoadHistoricalDataRequest.BarSize', 30)
        ONE_MINUTE = typing___cast('LoadHistoricalDataRequest.BarSize', 60)
        TWO_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 120)
        THREE_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 180)
        FIVE_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 300)
        TEN_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 600)
        FIFTEEN_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 900)
        TWENTY_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 1200)
        THIRTY_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 1800)
        ONE_HOUR = typing___cast('LoadHistoricalDataRequest.BarSize', 3600)
        TWO_HOURS = typing___cast('LoadHistoricalDataRequest.BarSize', 7200)
        THREE_HOURS = typing___cast('LoadHistoricalDataRequest.BarSize', 10800)
        FOUR_HOURS = typing___cast('LoadHistoricalDataRequest.BarSize', 14400)
        EIGHT_HOURS = typing___cast('LoadHistoricalDataRequest.BarSize', 28800)
        ONE_DAY = typing___cast('LoadHistoricalDataRequest.BarSize', 86400)
        ONE_WEEK = typing___cast('LoadHistoricalDataRequest.BarSize', 604800)
        ONE_MONTH = typing___cast('LoadHistoricalDataRequest.BarSize', 2592000)
    UNSPECIFIED_SIZE = typing___cast('LoadHistoricalDataRequest.BarSize', 0)
    ONE_SECOND = typing___cast('LoadHistoricalDataRequest.BarSize', 1)
    FIVE_SECONDS = typing___cast('LoadHistoricalDataRequest.BarSize', 5)
    TEN_SECONDS = typing___cast('LoadHistoricalDataRequest.BarSize', 10)
    FIFTEEN_SECONDS = typing___cast('LoadHistoricalDataRequest.BarSize', 15)
    THIRTY_SECONDS = typing___cast('LoadHistoricalDataRequest.BarSize', 30)
    ONE_MINUTE = typing___cast('LoadHistoricalDataRequest.BarSize', 60)
    TWO_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 120)
    THREE_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 180)
    FIVE_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 300)
    TEN_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 600)
    FIFTEEN_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 900)
    TWENTY_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 1200)
    THIRTY_MINUTES = typing___cast('LoadHistoricalDataRequest.BarSize', 1800)
    ONE_HOUR = typing___cast('LoadHistoricalDataRequest.BarSize', 3600)
    TWO_HOURS = typing___cast('LoadHistoricalDataRequest.BarSize', 7200)
    THREE_HOURS = typing___cast('LoadHistoricalDataRequest.BarSize', 10800)
    FOUR_HOURS = typing___cast('LoadHistoricalDataRequest.BarSize', 14400)
    EIGHT_HOURS = typing___cast('LoadHistoricalDataRequest.BarSize', 28800)
    ONE_DAY = typing___cast('LoadHistoricalDataRequest.BarSize', 86400)
    ONE_WEEK = typing___cast('LoadHistoricalDataRequest.BarSize', 604800)
    ONE_MONTH = typing___cast('LoadHistoricalDataRequest.BarSize', 2592000)

    class BarSource(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'LoadHistoricalDataRequest.BarSource': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['LoadHistoricalDataRequest.BarSource']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'LoadHistoricalDataRequest.BarSource']]: ...
        UNSPECIFIED_SOURCE = typing___cast('LoadHistoricalDataRequest.BarSource', 0)
        TRADES = typing___cast('LoadHistoricalDataRequest.BarSource', 1)
        MIDPOINT = typing___cast('LoadHistoricalDataRequest.BarSource', 2)
        BID = typing___cast('LoadHistoricalDataRequest.BarSource', 3)
        ASK = typing___cast('LoadHistoricalDataRequest.BarSource', 4)
        BID_ASK = typing___cast('LoadHistoricalDataRequest.BarSource', 5)
        ADJUSTED_LAST = typing___cast('LoadHistoricalDataRequest.BarSource', 6)
        HISTORICAL_VOLATILITY = typing___cast('LoadHistoricalDataRequest.BarSource', 7)
        OPTION_IMPLIED_VOLATILITY = typing___cast('LoadHistoricalDataRequest.BarSource', 8)
        REBATE_RATE = typing___cast('LoadHistoricalDataRequest.BarSource', 9)
        FEE_RATE = typing___cast('LoadHistoricalDataRequest.BarSource', 10)
        YIELD_BID = typing___cast('LoadHistoricalDataRequest.BarSource', 11)
        YIELD_ASK = typing___cast('LoadHistoricalDataRequest.BarSource', 12)
        YIELD_BID_ASK = typing___cast('LoadHistoricalDataRequest.BarSource', 13)
        YIELD_LAST = typing___cast('LoadHistoricalDataRequest.BarSource', 14)
    UNSPECIFIED_SOURCE = typing___cast('LoadHistoricalDataRequest.BarSource', 0)
    TRADES = typing___cast('LoadHistoricalDataRequest.BarSource', 1)
    MIDPOINT = typing___cast('LoadHistoricalDataRequest.BarSource', 2)
    BID = typing___cast('LoadHistoricalDataRequest.BarSource', 3)
    ASK = typing___cast('LoadHistoricalDataRequest.BarSource', 4)
    BID_ASK = typing___cast('LoadHistoricalDataRequest.BarSource', 5)
    ADJUSTED_LAST = typing___cast('LoadHistoricalDataRequest.BarSource', 6)
    HISTORICAL_VOLATILITY = typing___cast('LoadHistoricalDataRequest.BarSource', 7)
    OPTION_IMPLIED_VOLATILITY = typing___cast('LoadHistoricalDataRequest.BarSource', 8)
    REBATE_RATE = typing___cast('LoadHistoricalDataRequest.BarSource', 9)
    FEE_RATE = typing___cast('LoadHistoricalDataRequest.BarSource', 10)
    YIELD_BID = typing___cast('LoadHistoricalDataRequest.BarSource', 11)
    YIELD_ASK = typing___cast('LoadHistoricalDataRequest.BarSource', 12)
    YIELD_BID_ASK = typing___cast('LoadHistoricalDataRequest.BarSource', 13)
    YIELD_LAST = typing___cast('LoadHistoricalDataRequest.BarSource', 14)

    endTimestampUTC = ... # type: builtin___int
    barSize = ... # type: LoadHistoricalDataRequest.BarSize
    barSource = ... # type: LoadHistoricalDataRequest.BarSource
    regularTradingHoursOnly = ... # type: builtin___bool

    @property
    def contractSpecifier(self) -> ContractSpecifier: ...

    @property
    def duration(self) -> Duration: ...

    def __init__(self,
        *,
        contractSpecifier : typing___Optional[ContractSpecifier] = None,
        endTimestampUTC : typing___Optional[builtin___int] = None,
        duration : typing___Optional[Duration] = None,
        barSize : typing___Optional[LoadHistoricalDataRequest.BarSize] = None,
        barSource : typing___Optional[LoadHistoricalDataRequest.BarSource] = None,
        regularTradingHoursOnly : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> LoadHistoricalDataRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"contractSpecifier",u"duration"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"barSize",u"barSource",u"contractSpecifier",u"duration",u"endTimestampUTC",u"regularTradingHoursOnly"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"contractSpecifier",b"contractSpecifier",u"duration",b"duration"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"barSize",b"barSize",u"barSource",b"barSource",u"contractSpecifier",b"contractSpecifier",u"duration",b"duration",u"endTimestampUTC",b"endTimestampUTC",u"regularTradingHoursOnly",b"regularTradingHoursOnly"]) -> None: ...

class LoadHistoricalDataResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    backfillJobID = ... # type: typing___Text

    def __init__(self,
        *,
        backfillJobID : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> LoadHistoricalDataResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"backfillJobID"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"backfillJobID",b"backfillJobID"]) -> None: ...

class StartRealTimeDataRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class BarSource(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'StartRealTimeDataRequest.BarSource': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['StartRealTimeDataRequest.BarSource']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'StartRealTimeDataRequest.BarSource']]: ...
        UNSPECIFIED_SOURCE = typing___cast('StartRealTimeDataRequest.BarSource', 0)
        TRADES = typing___cast('StartRealTimeDataRequest.BarSource', 1)
        MIDPOINT = typing___cast('StartRealTimeDataRequest.BarSource', 2)
        BID = typing___cast('StartRealTimeDataRequest.BarSource', 3)
        ASK = typing___cast('StartRealTimeDataRequest.BarSource', 4)
    UNSPECIFIED_SOURCE = typing___cast('StartRealTimeDataRequest.BarSource', 0)
    TRADES = typing___cast('StartRealTimeDataRequest.BarSource', 1)
    MIDPOINT = typing___cast('StartRealTimeDataRequest.BarSource', 2)
    BID = typing___cast('StartRealTimeDataRequest.BarSource', 3)
    ASK = typing___cast('StartRealTimeDataRequest.BarSource', 4)

    barSource = ... # type: StartRealTimeDataRequest.BarSource
    regularTradingHoursOnly = ... # type: builtin___bool

    @property
    def contractSpecifier(self) -> ContractSpecifier: ...

    def __init__(self,
        *,
        contractSpecifier : typing___Optional[ContractSpecifier] = None,
        barSource : typing___Optional[StartRealTimeDataRequest.BarSource] = None,
        regularTradingHoursOnly : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> StartRealTimeDataRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"contractSpecifier"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"barSource",u"contractSpecifier",u"regularTradingHoursOnly"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"contractSpecifier",b"contractSpecifier"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"barSource",b"barSource",u"contractSpecifier",b"contractSpecifier",u"regularTradingHoursOnly",b"regularTradingHoursOnly"]) -> None: ...

class StartRealTimeDataResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    requestID = ... # type: typing___Text

    def __init__(self,
        *,
        requestID : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> StartRealTimeDataResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"requestID"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"requestID",b"requestID"]) -> None: ...

class CancelRealTimeDataRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    requestID = ... # type: typing___Text

    def __init__(self,
        *,
        requestID : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> CancelRealTimeDataRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"requestID"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"requestID",b"requestID"]) -> None: ...

class CancelRealTimeDataResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> CancelRealTimeDataResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class HealthCheckRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> HealthCheckRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class HealthCheckResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> HealthCheckResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
