name: Python

on:
  push:
    branches:
      - master
    
    tags:
      - v*
  
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      env:
        PIP_GITHUB_USER: ${{ secrets.PIP_GITHUB_USER }}
        PIP_GITHUB_PASSWORD: ${{ secrets.PIP_GITHUB_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Type-check
      run: |
        mypy .

    - name: Test
      run: |
        python -m unittest -v

    - name: Check formatting
      run: |
        black --check --exclude '(_pb2|ib[-_]insync)' .

  gpr:
    needs: build
    name: Push to GitHub Package Registry
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v1

    - uses: antequant/docker-push-action@v0.3.1
      with:
        docker_server: docker.pkg.github.com
        docker_password: ${{ secrets.GITHUB_TOKEN }}
        image_path: docker.pkg.github.com/${{ github.repository }}
  
  gcr:
    needs: build
    name: Push to Google Container Registry
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v1

    - uses: antequant/google-container-registry-push-action@v0.1
      with:
        gcp_email: ${{ secrets.GCP_USER }}
        gcp_token: ${{ secrets.GCP_TOKEN }}
        gcp_project: tradesponder