name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Mypy Check
      uses: jpetrucciani/mypy-check@0.730
    - name: Black Check
      uses: jpetrucciani/black-check@19.3b0
    - name: Test
      run: |
        python -m unittest -v
    - name: Test installing
      run: |
        pip install .
