name: Python

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Type-check
      run: |
        mypy .

    - name: Test
      run: |
        python -m unittest -v

    - name: Test installing
      run: |
        pip install .

    - name: Check formatting
      run: |
        black --check --exclude '_pb2' .
